create table public."TAROT_READING_LOG" (
  id bigint generated by default as identity,
  auth_id uuid not null,
  topic text not null,
  spread text not null,
  question text null,
  card_count smallint not null,
  cards jsonb not null,
  status text not null,
  model text null,
  error_code text null,
  error_message text null,
  client_ip text null,
  created_at timestamp with time zone not null default now(),
  constraint TAROT_READING_LOG_pkey primary key (id),
  constraint TAROT_READING_LOG_auth_id_fkey foreign KEY (auth_id) references public."USER_MST" (auth_id) on delete CASCADE,
  constraint TAROT_READING_LOG_status_check check (status in ('success', 'failed'))
) TABLESPACE pg_default;

create index IF not exists idx_tarot_reading_log_auth_id_created_at on public."TAROT_READING_LOG" using btree (auth_id, created_at desc) TABLESPACE pg_default;

alter table public."TAROT_READING_LOG" enable row level security;

create policy "tarot_reading_log_insert_own" on public."TAROT_READING_LOG" for INSERT to authenticated
with
  check (auth.uid () = auth_id);

create policy "tarot_reading_log_select_own" on public."TAROT_READING_LOG" for
select
  to authenticated using (auth.uid () = auth_id);
